name: lyricify_lyrics_helper
description: Dart implementation of Lyricify Lyrics Helper
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.4.0
  json_annotation: ^4.7.0
  pointycastle: ^3.7.3

  crypto: any
  convert: any
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.3.0
  build_runner: ^2.2.0
  mockito: ^5.4.4 