name: lyricify_lyrics_helper
description: Dart implementation of Lyricify Lyrics Helper
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  pointycastle: ^3.7.3
  xml: ^6.3.0

  crypto: any
  convert: any
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.3.0
  build_runner: ^2.2.0 